In [ ]:
!pip uninstall awp_protocol

Found existing installation: awp_protocol 0.3.1
Uninstalling awp_protocol-0.3.1:
  Would remove:
    /usr/local/lib/python3.12/dist-packages/actions/*
    /usr/local/lib/python3.12/dist-packages/awp_protocol-0.3.1.dist-info/*
    /usr/local/lib/python3.12/dist-packages/awp_protocol/*
    /usr/local/lib/python3.12/dist-packages/tests/*
  Would not remove (might be manually added):
    /usr/local/lib/python3.12/dist-packages/tests/cloud_database_test.py
    /usr/local/lib/python3.12/dist-packages/tests/conversion_test.py
    /usr/local/lib/python3.12/dist-packages/tests/graph_entities_test.py
    /usr/local/lib/python3.12/dist-packages/tests/graph_server_test.py
    /usr/local/lib/python3.12/dist-packages/tests/magics_test.py
    /usr/local/lib/python3.12/dist-packages/tests/node_expansion_test.py
    /usr/local/lib/python3.12/dist-packages/tests/sample_notebook_test.py
    /usr/local/lib/python3.12/dist-packages/tests/schema_manager_test.py
    /usr/local/lib/python3.12/dist-packages/te

In [ ]:
!pip install git+https://github.com/KarolKutyla/awp_tf_tests.git
from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf

from actions import models, datasets_v2, attacks

from awp_tf.attacks.v2 import pgd
from awp_tf import awp
from awp_tf import batch_processor
from awp_tf.callbacks import checkpoint_callback, epoch_logger

tf.config.run_functions_eagerly(False)

train_ds, tf_test_ds = datasets_v2.load_cifar_dataset()
steps_per_epoch = train_ds.cardinality()

attack_params = pgd.PGDParams(perturbation_bound=128/255, pgd_step=10, pgd_step_size=15/255, norm="l2")
protocol_params = batch_processor.AWPParams(alternate_iteration=1, awp_steps=1, weight_constraint=1.0e-2, step_size=1.0e-2)
awp_params = awp.Params(mode="trades", protocol_params=protocol_params)
params = awp.Params(protocol_params=protocol_params)

  Cloning https://****@github.com/KarolKutyla/AWPProtocol.git to /tmp/pip-req-build-ziron28o
  Running command git clone --filter=blob:none --quiet 'https://****@github.com/KarolKutyla/AWPProtocol.git' /tmp/pip-req-build-ziron28o
  Resolved https://****@github.com/KarolKutyla/AWPProtocol.git to commit 235d9e8aee4eba5e0d16065867fe40641e97a70f
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 650.7/650.7 kB 12.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 950.8/950.8 kB 49.1 MB/s eta 0:00:00
  Created wheel for awp_protocol: filename=awp_protocol-0.3.1-py3-none-any.whl size=31974 sha256=0bd1b1d5949dbb30036fbd3de06883553c58aae6df0abd9a598a27e79a6f6bfb
  Stored in directory: /tmp/pip-ephem-wheel-cache-1nr7ii94/wheels/53/a5/c2/422b3065f4b7b68a2cb854192837a10e595e0ef15b4a40567b
Successfully built awp_protocol
Mounted at /content/drive


Model: "resnet_18v2_normal"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 32, 32, 3) │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1_conv (Conv2D) │ (None, 16, 16,    │      9,472 │ input_layer[0][0] │
│                     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ pool1_pool          │ (None, 8, 8, 64)  │          0 │ conv1_conv[0][0]  │
│ (MaxPooling2D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 64)  │        256 │ pool1_pool[0][0]  │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 64)  │          0 │ v2_stack_0_block… │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 64)  │     36,864 │ v2_stack_0_block… │
│ (Conv2D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 64)  │        256 │ v2_stack_0_block… │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 64)  │          0 │ v2_stack_0_block… │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 64)  │     36,864 │ v2_stack_0_block… │
│ (Conv2D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 64)  │          0 │ pool1_pool[0][0], │
│ (Add)               │                   │            │ v2_stack_0_block… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block2_… │ (None, 8, 8, 64)  │        256 │ v2_stack_0_block… │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block2_… │ (None, 8, 8, 64)  │          0 │ v2_stack_0_block… │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block2_… │ (None, 8, 8, 64)  │     36,864 │ v2_stack_0_block… │
│ (Conv2D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block2_… │ (None, 8, 8, 64)  │        256 │ v2_stack_0_block… │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block2_… │ (None, 8, 8, 64)  │          0 │ v2_stack_0_block… │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block2_… │ (None, 8, 8, 64)  │     36,864 │ v2_stack_0_block… │
│ (Conv2D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block2_… │ (None, 8, 8, 64)  │          0 │ v2_stack_0_block

 Total params: 11,188,618 (42.68 MB)

 Trainable params: 11,180,810 (42.65 MB)

 Non-trainable params: 7,808 (30.50 KB)

Model: "resnet_152v2_awp"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_1       │ (None, 32, 32, 3) │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1_conv (Conv2D) │ (None, 16, 16,    │      9,472 │ input_layer_1[0]… │
│                     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ pool1_pool          │ (None, 8, 8, 64)  │          0 │ conv1_conv[0][0]  │
│ (MaxPooling2D)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 64)  │        256 │ pool1_pool[0][0]  │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 64)  │          0 │ v2_stack_0_block… │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 64)  │      4,096 │ v2_stack_0_block… │
│ (Conv2D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 64)  │        256 │ v2_stack_0_block… │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 64)  │          0 │ v2_stack_0_block… │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 64)  │     36,864 │ v2_stack_0_block… │
│ (Conv2D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 64)  │        256 │ v2_stack_0_block… │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 64)  │          0 │ v2_stack_0_block… │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 256) │     16,640 │ v2_stack_0_block… │
│ (Conv2D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 256) │     16,640 │ v2_stack_0_block… │
│ (Conv2D)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block1_… │ (None, 8, 8, 256) │          0 │ v2_stack_0_block… │
│ (Add)               │                   │            │ v2_stack_0_block… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block2_… │ (None, 8, 8, 256) │      1,024 │ v2_stack_0_block… │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block2_… │ (None, 8, 8, 256) │          0 │ v2_stack_0_block… │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ v2_stack_0_block2_… │ (None, 8, 8, 64)  │     16,384 │ v2_stack_0_block

 Total params: 58,352,138 (222.60 MB)

 Trainable params: 58,208,394 (222.05 MB)

 Non-trainable params: 143,744 (561.50 KB)

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


Resnet standard training

In [ ]:
model = models.load_wide_resnet_standard(steps_per_epoch)
model.summary()
print(model.summary())

pgd_attack = pgd.PGDAttack(model, attack_params)

trainer = awp.Trainer(model, pgd_attack, warmup=0, params=params)

save_callback = checkpoint_callback.EpochCheckpoint(f"/content/drive/MyDrive/checkpoints/{model.name}")
epoch_logger_callback = epoch_logger.EpochLogger(save_filepath=f"/content/drive/MyDrive/logs/{model.name}/logs.txt", attack_params=attack_params, training_params=awp_params)
callbacks = [save_callback, epoch_logger_callback]

trainer.fit_dataset(train_ds, validation_dataset=tf_test_ds, nb_epochs=200, callbacks=callbacks, enable_adversarial=False)

Model: "wide_resnet_standard_training"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_2       │ (None, 32, 32, 3) │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ zero_padding2d      │ (None, 34, 34, 3) │          0 │ input_layer_2[0]… │
│ (ZeroPadding2D)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d (Conv2D)     │ (None, 32, 32,    │        432 │ zero_padding2d[0… │
│                     │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalization │ (None, 32, 32,    │         64 │ conv2d[0][0]      │
│ (BatchNormalizatio… │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation          │ (None, 32, 32,    │          0 │ batch_normalizat… │
│ (Activation)        │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ zero_padding2d_1    │ (None, 34, 34,    │          0 │ activation[0][0]  │
│ (ZeroPadding2D)     │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_1 (Conv2D)   │ (None, 32, 32,    │     23,040 │ zero_padding2d_1… │
│                     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 32, 32,    │        640 │ conv2d_1[0][0]    │
│ (BatchNormalizatio… │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_1        │ (None, 32, 32,    │          0 │ batch_normalizat… │
│ (Activation)        │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 32, 32,    │          0 │ activation_1[0][… │
│                     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ zero_padding2d_2    │ (None, 34, 34,    │          0 │ dropout[0][0]     │
│ (ZeroPadding2D)     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_2 (Conv2D)   │ (None, 32, 32,    │    230,400 │ zero_padding2d_2… │
│                     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_3 (Conv2D)   │ (None, 32, 32,    │      2,560 │ activation[0][0]  │
│                     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add (Add)           │ (None, 32, 32,    │          0 │ conv2d_2[0][0],   │
│                     │ 160)              │            │ conv2d_3[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 32, 32,    │        640 │ add[0][0]         │
│ (BatchNormalizatio… │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_2        │ (None, 32, 32,    │          0 │ batch_normalizat… │
│ (Activation)        │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ zero_padding2d_3    │ (None, 34, 34,    │          0 │ activation_2[0][

 Total params: 36,497,146 (139.23 MB)

 Trainable params: 36,479,194 (139.16 MB)

 Non-trainable params: 17,952 (70.12 KB)

Model: "wide_resnet_standard_training"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_2       │ (None, 32, 32, 3) │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ zero_padding2d      │ (None, 34, 34, 3) │          0 │ input_layer_2[0]… │
│ (ZeroPadding2D)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d (Conv2D)     │ (None, 32, 32,    │        432 │ zero_padding2d[0… │
│                     │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalization │ (None, 32, 32,    │         64 │ conv2d[0][0]      │
│ (BatchNormalizatio… │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation          │ (None, 32, 32,    │          0 │ batch_normalizat… │
│ (Activation)        │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ zero_padding2d_1    │ (None, 34, 34,    │          0 │ activation[0][0]  │
│ (ZeroPadding2D)     │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_1 (Conv2D)   │ (None, 32, 32,    │     23,040 │ zero_padding2d_1… │
│                     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 32, 32,    │        640 │ conv2d_1[0][0]    │
│ (BatchNormalizatio… │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_1        │ (None, 32, 32,    │          0 │ batch_normalizat… │
│ (Activation)        │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 32, 32,    │          0 │ activation_1[0][… │
│                     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ zero_padding2d_2    │ (None, 34, 34,    │          0 │ dropout[0][0]     │
│ (ZeroPadding2D)     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_2 (Conv2D)   │ (None, 32, 32,    │    230,400 │ zero_padding2d_2… │
│                     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_3 (Conv2D)   │ (None, 32, 32,    │      2,560 │ activation[0][0]  │
│                     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add (Add)           │ (None, 32, 32,    │          0 │ conv2d_2[0][0],   │
│                     │ 160)              │            │ conv2d_3[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 32, 32,    │        640 │ add[0][0]         │
│ (BatchNormalizatio… │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_2        │ (None, 32, 32,    │          0 │ batch_normalizat… │
│ (Activation)        │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ zero_padding2d_3    │ (None, 34, 34,    │          0 │ activation_2[0][

 Total params: 36,497,146 (139.23 MB)

 Trainable params: 36,479,194 (139.16 MB)

 Non-trainable params: 17,952 (70.12 KB)

None
391/391 ━━━━━━━━━━━━━━━━━━━━ 132s 339ms/step - loss: 1.7589 - acc: 0.2331 - robust_loss: 1.7589 - robust_acc: 0.2331
391/391 ━━━━━━━━━━━━━━━━━━━━ 88s 226ms/step - loss: 1.1188 - acc: 0.5652 - robust_loss: 1.1188 - robust_acc: 0.5652
391/391 ━━━━━━━━━━━━━━━━━━━━ 88s 226ms/step - loss: 0.9016 - acc: 0.6659 - robust_loss: 0.9016 - robust_acc: 0.6659
391/391 ━━━━━━━━━━━━━━━━━━━━ 88s 226ms/step - loss: 0.7336 - acc: 0.7330 - robust_loss: 0.7336 - robust_acc: 0.7330
391/391 ━━━━━━━━━━━━━━━━━━━━ 88s 226ms/step - loss: 0.6233 - acc: 0.7759 - robust_loss: 0.6233 - robust_acc: 0.7759
391/391 ━━━━━━━━━━━━━━━━━━━━ 88s 226ms/step - loss: 0.5551 - acc: 0.8040 - robust_loss: 0.5551 - robust_acc: 0.8040
391/391 ━━━━━━━━━━━━━━━━━━━━ 88s 226ms/step - loss: 0.5001 - acc: 0.8266 - robust_loss: 0.5001 - robust_acc: 0.8266
391/391 ━━━━━━━━━━━━━━━━━━━━ 88s 226ms/step - loss: 0.4557 - acc: 0.8408 - robust_loss: 0.4557 - robust_acc: 0.8408
391/391 ━━━━━━━━━━━━━━━━━━━━ 88s 226ms/step - loss: 0.4196 - acc: 

In [ ]:
model = models.load_wide_resnet_adversarial(steps_per_epoch)
model.summary()
print(model.summary())

pgd_attack = pgd.PGDAttack(model, attack_params)

trainer = awp.Trainer(model, pgd_attack, warmup=200, params=params)

save_callback = checkpoint_callback.EpochCheckpoint(f"/content/drive/MyDrive/checkpoints/{model.name}")
epoch_logger_callback = epoch_logger.EpochLogger(save_filepath=f"/content/drive/MyDrive/logs/{model.name}/logs.txt", attack_params=attack_params, training_params=awp_params)
callbacks = [save_callback, epoch_logger_callback]

trainer.fit_dataset(train_ds, validation_dataset=tf_test_ds, nb_epochs=200, callbacks=callbacks)

Model: "wide_resnet_adversarial_training"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_3       │ (None, 32, 32, 3) │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ zero_padding2d_25   │ (None, 34, 34, 3) │          0 │ input_layer_3[0]… │
│ (ZeroPadding2D)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_28 (Conv2D)  │ (None, 32, 32,    │        432 │ zero_padding2d_2… │
│                     │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 32, 32,    │         64 │ conv2d_28[0][0]   │
│ (BatchNormalizatio… │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_25       │ (None, 32, 32,    │          0 │ batch_normalizat… │
│ (Activation)        │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ zero_padding2d_26   │ (None, 34, 34,    │          0 │ activation_25[0]… │
│ (ZeroPadding2D)     │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_29 (Conv2D)  │ (None, 32, 32,    │     23,040 │ zero_padding2d_2… │
│                     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 32, 32,    │        640 │ conv2d_29[0][0]   │
│ (BatchNormalizatio… │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_26       │ (None, 32, 32,    │          0 │ batch_normalizat… │
│ (Activation)        │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_12          │ (None, 32, 32,    │          0 │ activation_26[0]… │
│ (Dropout)           │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ zero_padding2d_27   │ (None, 34, 34,    │          0 │ dropout_12[0][0]  │
│ (ZeroPadding2D)     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_30 (Conv2D)  │ (None, 32, 32,    │    230,400 │ zero_padding2d_2… │
│                     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_31 (Conv2D)  │ (None, 32, 32,    │      2,560 │ activation_25[0]… │
│                     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_12 (Add)        │ (None, 32, 32,    │          0 │ conv2d_30[0][0],  │
│                     │ 160)              │            │ conv2d_31[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 32, 32,    │        640 │ add_12[0][0]      │
│ (BatchNormalizatio… │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_27       │ (None, 32, 32,    │          0 │ batch_normalizat… │
│ (Activation)        │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ zero_padding2d_28   │ (None, 34, 34,    │          0 │ activation_27[0]

 Total params: 36,497,146 (139.23 MB)

 Trainable params: 36,479,194 (139.16 MB)

 Non-trainable params: 17,952 (70.12 KB)

Model: "wide_resnet_adversarial_training"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_3       │ (None, 32, 32, 3) │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ zero_padding2d_25   │ (None, 34, 34, 3) │          0 │ input_layer_3[0]… │
│ (ZeroPadding2D)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_28 (Conv2D)  │ (None, 32, 32,    │        432 │ zero_padding2d_2… │
│                     │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 32, 32,    │         64 │ conv2d_28[0][0]   │
│ (BatchNormalizatio… │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_25       │ (None, 32, 32,    │          0 │ batch_normalizat… │
│ (Activation)        │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ zero_padding2d_26   │ (None, 34, 34,    │          0 │ activation_25[0]… │
│ (ZeroPadding2D)     │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_29 (Conv2D)  │ (None, 32, 32,    │     23,040 │ zero_padding2d_2… │
│                     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 32, 32,    │        640 │ conv2d_29[0][0]   │
│ (BatchNormalizatio… │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_26       │ (None, 32, 32,    │          0 │ batch_normalizat… │
│ (Activation)        │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_12          │ (None, 32, 32,    │          0 │ activation_26[0]… │
│ (Dropout)           │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ zero_padding2d_27   │ (None, 34, 34,    │          0 │ dropout_12[0][0]  │
│ (ZeroPadding2D)     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_30 (Conv2D)  │ (None, 32, 32,    │    230,400 │ zero_padding2d_2… │
│                     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_31 (Conv2D)  │ (None, 32, 32,    │      2,560 │ activation_25[0]… │
│                     │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_12 (Add)        │ (None, 32, 32,    │          0 │ conv2d_30[0][0],  │
│                     │ 160)              │            │ conv2d_31[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 32, 32,    │        640 │ add_12[0][0]      │
│ (BatchNormalizatio… │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_27       │ (None, 32, 32,    │          0 │ batch_normalizat… │
│ (Activation)        │ 160)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ zero_padding2d_28   │ (None, 34, 34,    │          0 │ activation_27[0]

 Total params: 36,497,146 (139.23 MB)

 Trainable params: 36,479,194 (139.16 MB)

 Non-trainable params: 17,952 (70.12 KB)

None
391/391 ━━━━━━━━━━━━━━━━━━━━ 337s 862ms/step - loss: 1.8297 - acc: 0.2220 - robust_loss: 0.9274 - robust_acc: 0.1820
391/391 ━━━━━━━━━━━━━━━━━━━━ 254s 650ms/step - loss: 1.2860 - acc: 0.5055 - robust_loss: 0.6824 - robust_acc: 0.3205
391/391 ━━━━━━━━━━━━━━━━━━━━ 254s 649ms/step - loss: 1.0502 - acc: 0.6180 - robust_loss: 0.5778 - robust_acc: 0.3983
391/391 ━━━━━━━━━━━━━━━━━━━━ 254s 649ms/step - loss: 0.9049 - acc: 0.6772 - robust_loss: 0.5126 - robust_acc: 0.4514
391/391 ━━━━━━━━━━━━━━━━━━━━ 254s 649ms/step - loss: 0.7937 - acc: 0.7233 - robust_loss: 0.4626 - robust_acc: 0.4881
391/391 ━━━━━━━━━━━━━━━━━━━━ 254s 649ms/step - loss: 0.7170 - acc: 0.7543 - robust_loss: 0.4273 - robust_acc: 0.5250
391/391 ━━━━━━━━━━━━━━━━━━━━ 254s 649ms/step - loss: 0.6550 - acc: 0.7784 - robust_loss: 0.3989 - robust_acc: 0.5566
391/391 ━━━━━━━━━━━━━━━━━━━━ 254s 650ms/step - loss: 0.6134 - acc: 0.7961 - robust_loss: 0.3792 - robust_acc: 0.5758
391/391 ━━━━━━━━━━━━━━━━━━━━ 254s 649ms/step - loss: 0.5696

In [ ]:
model.fit(train_ds, epochs=20)

Epoch 1/20
391/391 ━━━━━━━━━━━━━━━━━━━━ 73s 125ms/step - accuracy: 0.3403 - loss: 1.7175
Epoch 2/20
391/391 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.5828 - loss: 1.1432
Epoch 3/20
391/391 ━━━━━━━━━━━━━━━━━━━━ 32s 80ms/step - accuracy: 0.6854 - loss: 0.8780
Epoch 4/20
120/391 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.7298 - loss: 0.7693

KeyboardInterrupt: 

In [ ]:
model = models.load_wide_resnet_adversarial(steps_per_epoch)

pgd_attack = pgd.PGDAttack(model, attack_params)

trainer = awp.Trainer(model, pgd_attack, warmup=0, params=params)

save_callback = checkpoint_callback.EpochCheckpoint(f"/content/drive/MyDrive/checkpoints/{model.name}")
epoch_logger_callback = epoch_logger.EpochLogger(save_filepath=f"/content/drive/MyDrive/logs/{model.name}/logs.txt", attack_params=attack_params, training_params=awp_params)
callbacks = [save_callback, epoch_logger_callback]

trainer.fit_dataset(train_ds, validation_dataset=tf_test_ds, nb_epochs=200, callbacks=callbacks)

100%|██████████| 877/877 [00:00<00:00, 2.19MB/s]


170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 4s 0us/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 2.3140
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.3963
391/391 ━━━━━━━━━━━━━━━━━━━━ 39s 101ms/step - loss: 1.8229 - acc: 0.2521 - robust_loss: 1.8229 - robust_acc: 0.2521
391/391 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - loss: 1.4627 - acc: 0.4471 - robust_loss: 1.4627 - robust_acc: 0.4471
391/391 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - loss: 1.2966 - acc: 0.5163 - robust_loss: 1.2966 - robust_acc: 0.5163
391/391 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - loss: 1.1573 - acc: 0.5788 - robust_loss: 1.1573 - robust_acc: 0.5788
391/391 ━━━━━━━━━━━━━━━━━━━━ 15s 39ms/step - loss: 1.0416 - acc: 0.6285 - robust_loss: 1.0416 - robust_acc: 0.6285
391/391 ━━━━━━━━━━━━━━━━━━━━ 15s 40ms/step - loss: 0.9586 - acc: 0.6593 - robust_loss: 0.9586 - robust_acc: 0.6593
391/391 ━━━━━━━━━━━━━━━━━━━━ 16s 40ms/step - loss: 0.8887 - acc: 0.6876 - robust_loss: 0.8887 - robust_acc: 0.6876
391/391 ━━━━━━━━━━━━━━━━━━━━ 15s 39

In [ ]:
model = models.load_tensorflow_resnet_18_v2_for_adversarial_training(steps_per_epoch)
pgd_attack = pgd.PGDAttack(model, attack_params)
trainer = awp.AdversarialTrainerAWPTensorflow(model, pgd_attack, warmup=200, params=params)
save_callback = checkpoint_callback.EpochCheckpoint(f"/content/drive/MyDrive/checkpoints/{model.name}")
epoch_logger_callback = epoch_logger.EpochLogger(save_filepath=f"/content/drive/MyDrive/logs/{model.name}/logs.txt", attack_params=attack_params, training_params=awp_params)
callbacks = [save_callback, epoch_logger_callback]

trainer.fit_dataset(train_ds, validation_dataset=tf_test_ds, nb_epochs=200, callbacks=callbacks)

4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 2.3061
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.3850
391/391 ━━━━━━━━━━━━━━━━━━━━ 85s 216ms/step - loss: 1.9342 - acc: 0.2858 - robust_loss: 0.9780 - robust_acc: 0.2480
391/391 ━━━━━━━━━━━━━━━━━━━━ 31s 79ms/step - loss: 1.4432 - acc: 0.4618 - robust_loss: 0.7416 - robust_acc: 0.3261
391/391 ━━━━━━━━━━━━━━━━━━━━ 31s 78ms/step - loss: 1.2704 - acc: 0.5305 - robust_loss: 0.6631 - robust_acc: 0.3613
391/391 ━━━━━━━━━━━━━━━━━━━━ 30s 78ms/step - loss: 1.1358 - acc: 0.5891 - robust_loss: 0.6038 - robust_acc: 0.3952
391/391 ━━━━━━━━━━━━━━━━━━━━ 31s 78ms/step - loss: 1.0313 - acc: 0.6317 - robust_loss: 0.5576 - robust_acc: 0.4264
391/391 ━━━━━━━━━━━━━━━━━━━━ 31s 78ms/step - loss: 0.9492 - acc: 0.6672 - robust_loss: 0.5215 - robust_acc: 0.4494
391/391 ━━━━━━━━━━━━━━━━━━━━ 30s 78ms/step - loss: 0.8866 - acc: 0.6861 - robust_loss: 0.4939 - robust_acc: 0.4652
391/391 ━━━━━━━━━━━━━━━━━━━━ 31s 78ms/step - loss: 0.8333 - acc: 0.7054 - robust_loss: 0

In [ ]:
model = models.load_tensorflow_resnet_18_v2_for_awp_training(steps_per_epoch)
pgd_attack = pgd.PGDAttack(model, attack_params)
trainer = awp.AdversarialTrainerAWPTensorflow(model, pgd_attack, warmup=0, params=params)
save_callback = checkpoint_callback.EpochCheckpoint(f"/content/drive/MyDrive/checkpoints/{model.name}")
epoch_logger_callback = epoch_logger.EpochLogger(save_filepath=f"/content/drive/MyDrive/logs/{model.name}/logs.txt", attack_params=attack_params, training_params=awp_params)
callbacks = [save_callback, epoch_logger_callback]

trainer.fit_dataset(train_ds, validation_dataset=tf_test_ds, nb_epochs=200, callbacks=callbacks)

4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 2.3030
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.3790
391/391 ━━━━━━━━━━━━━━━━━━━━ 95s 242ms/step - loss: 2.3875 - acc: 0.2098 - robust_loss: 1.2024 - robust_acc: 0.1839
391/391 ━━━━━━━━━━━━━━━━━━━━ 34s 87ms/step - loss: 1.9297 - acc: 0.2983 - robust_loss: 0.9754 - robust_acc: 0.2313
391/391 ━━━━━━━━━━━━━━━━━━━━ 34s 86ms/step - loss: 1.7541 - acc: 0.3492 - robust_loss: 0.8898 - robust_acc: 0.2549
391/391 ━━━━━━━━━━━━━━━━━━━━ 34s 86ms/step - loss: 1.6554 - acc: 0.3794 - robust_loss: 0.8416 - robust_acc: 0.2688
391/391 ━━━━━━━━━━━━━━━━━━━━ 34s 86ms/step - loss: 1.5776 - acc: 0.4075 - robust_loss: 0.8048 - robust_acc: 0.2834
391/391 ━━━━━━━━━━━━━━━━━━━━ 34s 86ms/step - loss: 1.5175 - acc: 0.4367 - robust_loss: 0.7774 - robust_acc: 0.2945
391/391 ━━━━━━━━━━━━━━━━━━━━ 34s 86ms/step - loss: 1.4651 - acc: 0.4531 - robust_loss: 0.7537 - robust_acc: 0.3057
391/391 ━━━━━━━━━━━━━━━━━━━━ 34s 86ms/step - loss: 1.4094 - acc: 0.4767 - robust_loss: 0

In [ ]:
model = models.load_tensorflow_resnet_50_v2(steps_per_epoch)
pgd_attack = pgd.PGDAttack(model, attack_params)
trainer = awp.AdversarialTrainerAWPTensorflow(model, pgd_attack, warmup=0, params=params)
save_callback = checkpoint_callback.EpochCheckpoint(f"/content/drive/MyDrive/checkpoints/{model.name}")
epoch_logger_callback = epoch_logger.EpochLogger(save_filepath=f"/content/drive/MyDrive/logs/{model.name}/logs.txt", attack_params=attack_params, training_params=awp_params)
callbacks = [save_callback, epoch_logger_callback]

trainer.fit_dataset(train_ds, validation_dataset=tf_test_ds, nb_epochs=200, callbacks=callbacks)

100%|██████████| 871/871 [00:00<00:00, 1.55MB/s]


391/391 ━━━━━━━━━━━━━━━━━━━━ 209s 534ms/step - loss: 3.2734 - acc: 0.1836 - robust_loss: 1.6432 - robust_acc: 0.1726
391/391 ━━━━━━━━━━━━━━━━━━━━ 55s 141ms/step - loss: 2.0607 - acc: 0.2403 - robust_loss: 1.0358 - robust_acc: 0.1905
391/391 ━━━━━━━━━━━━━━━━━━━━ 55s 141ms/step - loss: 1.9267 - acc: 0.2791 - robust_loss: 0.9714 - robust_acc: 0.2057
391/391 ━━━━━━━━━━━━━━━━━━━━ 55s 141ms/step - loss: 1.8596 - acc: 0.3038 - robust_loss: 0.9390 - robust_acc: 0.2182
391/391 ━━━━━━━━━━━━━━━━━━━━ 55s 141ms/step - loss: 1.8091 - acc: 0.3270 - robust_loss: 0.9147 - robust_acc: 0.2297
391/391 ━━━━━━━━━━━━━━━━━━━━ 55s 141ms/step - loss: 1.7739 - acc: 0.3415 - robust_loss: 0.8979 - robust_acc: 0.2357
391/391 ━━━━━━━━━━━━━━━━━━━━ 55s 141ms/step - loss: 1.7449 - acc: 0.3511 - robust_loss: 0.8837 - robust_acc: 0.2458
391/391 ━━━━━━━━━━━━━━━━━━━━ 55s 141ms/step - loss: 1.7162 - acc: 0.3627 - robust_loss: 0.8701 - robust_acc: 0.2485
391/391 ━━━━━━━━━━━━━━━━━━━━ 55s 141ms/step - loss: 1.6941 - acc: 0.375

In [ ]:
import tensorflow as tf

from actions import models, datasets_v2, attacks

from awp_protocol.attacks.v2 import pgd
from awp_protocol import awp_no_proxy as awp
from awp_protocol import batch_processor_no_proxy as batch_processor
from awp_protocol.callbacks import checkpoint_callback, epoch_logger

train_ds, tf_test_ds = datasets_v2.load_cifar_dataset()
steps_per_epoch = train_ds.cardinality()
model = models.load_tensorflow_resnet_18_v2_for_awp_training(steps_per_epoch)
model.fit(train_ds, epochs=200)

Epoch 1/200
391/391 ━━━━━━━━━━━━━━━━━━━━ 30s 32ms/step - loss: 1.9233
Epoch 2/200
391/391 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 1.4367
Epoch 3/200
391/391 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 1.2464
Epoch 4/200
391/391 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 1.1044
Epoch 5/200
391/391 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 0.9968
Epoch 6/200
391/391 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 0.9135
Epoch 7/200
391/391 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 0.8466
Epoch 8/200
391/391 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 0.7840
Epoch 9/200
391/391 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 0.7410
Epoch 10/200
391/391 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 0.7033
Epoch 11/200
391/391 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 0.6611
Epoch 12/200
391/391 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 0.6372
Epoch 13/200
391/391 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 0.6086
Epoch 14/200
391/391 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 0.5822
Epoch 15/200
391/391 ━━━━━━━

In [ ]:
eval = model.evaluate(tf_test_ds)
print(eval)
eval = model.evaluate(train_ds)
print(eval)


79/79 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 0.8775 - loss: 0.6695
[0.6694920659065247, 0.8774999976158142]
384/391 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9991 - loss: 0.0036

In [ ]:
for x, y in train_ds.take(1):
  print(x)
  print(y)

tf.Tensor(
[[[[ 0.14509809  0.00392163  0.00392163]
   [ 0.17647064  0.0196079  -0.01176471]
   [ 0.32549024  0.12156868  0.02745104]
   ...
   [-1.         -1.         -1.        ]
   [-1.         -1.         -1.        ]
   [-1.         -1.         -1.        ]]

  [[ 0.14509809 -0.00392157  0.02745104]
   [ 0.22352946  0.04313731  0.01176476]
   [ 0.32549024  0.10588241 -0.01960784]
   ...
   [-1.         -1.         -1.        ]
   [-1.         -1.         -1.        ]
   [-1.         -1.         -1.        ]]

  [[ 0.19215691  0.0196079   0.04313731]
   [ 0.254902    0.0196079  -0.02745098]
   [ 0.26274514  0.00392163 -0.09803921]
   ...
   [-1.         -1.         -1.        ]
   [-1.         -1.         -1.        ]
   [-1.         -1.         -1.        ]]

  ...

  [[-1.         -1.         -1.        ]
   [-1.         -1.         -1.        ]
   [-1.         -1.         -1.        ]
   ...
   [-1.         -1.         -1.        ]
   [-1.         -1.         -1.        ]
   [-

In [ ]:
model.compile(
    # loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    # optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=['accuracy'])

In [ ]:
model = models.load_tensorflow_resnet_18_v2(steps_per_epoch)

attack_params = pgd.PGDParams(perturbation_bound=128/255, pgd_step=10, pgd_step_size=15/255, norm="l2")
pgd_attack = pgd.PGDAttack(model, attack_params)
x_batch, y_batch = next(iter(train_ds))
x_adv = pgd_attack.generate(x_batch, y_batch)
tf_evaluation_clean = model.evaluate(x_batch, y_batch)
tf_evaluation_adv = model.evaluate(x_adv, y_batch)

# labels = datasets.load_cifar_labels()
# plotter = attacks.AdversarialPlots(pgd_attack, labels)
# plotter.generate_and_show_adversarial_batch(x_batch, y_batch)

protocol_params = batch_processor.AWPParams(alternate_iteration=10, awp_steps=10, weight_constraint=1.0e-2)
awp_params = awp.Params(mode="trades", protocol_params=protocol_params)

params = awp.Params(protocol_params=protocol_params)
trainer = awp.AdversarialTrainerAWPTensorflow(model, pgd_attack, warmup=0, params=params)

save_callback = checkpoint_callback.EpochCheckpoint(f"checkpoints/{model.name}")
epoch_logger_callback = epoch_logger.EpochLogger(save_filepath=f"logs/{model.name}/logs.txt", attack_params=attack_params, training_params=awp_params)
callbacks = [save_callback, epoch_logger_callback]

trainer.fit_dataset(train_ds, validation_dataset=None, nb_epochs=2, callbacks=callbacks)

4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 2.3122
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.3263
 80/391 ━━━━━━━━━━━━━━━━━━━━ 18:38 4s/step - loss: 3.2711 - acc: 0.0600 - robust_loss: 3.2711 - robust_acc: 0.0600

KeyboardInterrupt: 

In [ ]:
train_ds, tf_test_ds = datasets_v2.load_cifar_dataset()
steps_per_epoch = train_ds.cardinality()
model = models.load_wide_resnet(steps_per_epoch)
model.fit(train_ds, epochs=2)

Epoch 1/2
 98/391 ━━━━━━━━━━━━━━━━━━━━ 1:22 280ms/step - loss: 11.6990

KeyboardInterrupt: 